### PR TITLE
Website design

### LINKED ISSUE #8: Setup index.html of the new dashboard
Create a homepage for the dashboard which includes links to other pages (leaderboard, packs etc.) and some basic information about the Discord server, including the invite link.

### LINKED ISSUE #9: Setup style for packs.html
Currently, packs.html is just a basic playground for all the features it will later host. To make it usable for people, a new style must be setup with test code removed/reworked.

### PR DESCRIPTION
**Pull request by noClaps**
### Description

Added styles for index and packs pages.

Fixes #8 
Fixes #9 

### Type of Change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

### Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by MesterMan03 — CHANGES_REQUESTED** [review]
Review 1:
- [ ] All sites should have a universal header to quickly jump between pages, currently if you're on leaderboard or packs you simply can't go back or anywhere else.
- [ ] The pack selection for the comments looks bland with its default theme (which is heavily dictated by the browser too), it should have an actual design which better fits the rest of the site, maybe even have some QoL features from https://github.com/MesterMan03/Bedlessbot/pull/10 (@jonahlikescookies).
- Concerns about comments:
  - [ ] It doesn't look like pages are handled - every /api/comments call only gets 10 comments max per pack per page. To fix this, `/api/comments/maxpage?packid=<pack id>` has been added to query the maximum page available, so now it just needs a simple page selector (infinite scrolling doesn't make much sense for this).
  - [x] If the user doesn't have a profile picture, the default discord avatar gets inserted which isn't sized properly. image
  - [ ] Scrolling is really choppy; the comments and packs should have separate scrolling (see [video](https://github.com/MesterMan03/Bedlessbot/assets/48682374/6b575075-72a0-4aef-a9ea-b3fdf1bd7fa9)).
- [x] Currently, the modal's proportions are gigantic, this should be reduced. image

**Comment by noClaps** [comment]
@jonahlikescookies If you'd like to work on some of these changes feel free to do so.

**Review by MesterMan03 — COMMENTED** [review]
After more testing, here is a review 2:
- [ ] Mobile layout is completely missing. (Since most people will use computers to download the resource packs, I think it's fine if we delay this after the public release has come out)
- [x] Currently the main page has the "Enable Notifications" button which is required for push notifications. This should be replaced by a more situational button, which could be shown when the user submits a comment. (I'll work on this)
- [x] The pack icons are still PNGs *and* they are not lazily loaded, which makes the site serve 6 megabytes of resources. Since the CDN is something only I have access to, I'll convert them to WebP soon and update the script to use webp files instead of png.
- [ ] The `date` field of comments are not used at all. This should be used with combination of `luxon` to parse and display localised dates.

**Comment by MesterMan03** [comment]
Ok so I've added the "Enable Notifications" button to the comment success modal, but make sure to check if it needs any styling.

**Comment by MesterMan03** [comment]
- [ ] Adding to the `date` value for comments being used, the individual comment layout could probably use a refresh. The avatar is too big, it leaves a bunch of space behind and it just doesn't look nice. Here is a little sketch of what I think it could look like. 
image

**Comment by jonahlikescookies** [comment]
Due to the size of the section for comments, very little of people’s usernames are shown(only 2 characters in this case).
IMG_1005
If we go off of the initial sketch, then we should definitely increase the width available to use. However, that would make the grid layout not fit, as currently, it barely does. Any ideas on how to fix this?

**Comment by MesterMan03** [comment]
Probably the best solution would be to move the date below the username. There should be enough space next to the avatar.
image

**Comment by MesterMan03** [comment]
I've also tried my best to create a mobile layout. I'd say it's pretty usable, but it definitely needs some minor adjustments, the image inside the comment toggle button looks a bit off for example and the pure black background for the comments in mobile layout is not final, I just set a random color as a placeholder.

**Review by MesterMan03 — COMMENTED** [review]
LGTM

**Review by MesterMan03 — APPROVED** [review]

**Pull request merged**
